### ISSUE TITLE
Call Sound Drop

### ISSUE THREAD

**Issue by mzahirr** [ringcentral/ringcentral-embeddable#478] opened 2021-02-11 15:08 UTC
1) I received a call with the ringcentral app open and I answered this call.
2) If a direct call (By using the agent's number like +1 740 000 000) came while I'm on call;
3)  We forward the incoming call to another number. Using the method below
     https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md#forward-a-ringing-call
4. Incoming call causes the 1st call's sound to drop and the agent becomes unavailable to hear any sound from ongoing call

Note :The problem can be solved by Holding and Unholding the call for now.

Can you please check ?

**Comment by embbnux** [comment] 2021-02-12 03:52
@mzahirr  Thanks so much for details steps. The root cause that app accept the call and transfer when app [forward](https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/session.ts#L698).  So the media resource is got when call is accepted. 
Let me find how to fix this.

**Comment by mzahirr** [comment] 2021-03-22 14:39
Hi @embbnux , I have re-deploy this version (master branch). And we trying to following steps

1. I received a call with the ringcentral app open and I answered this call.
2. If a direct call (By using the agent's number like +1 740 000 000) came while I'm on call;
3. We forward the incoming call to another number. Using the method below
4. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/control-widget.md#forward-a-ringing-call
5. Incoming call causes the 1st call's sound to drop and the agent becomes unavailable to hear any sound from ongoing call

But problem still persists. Could you please investigate ?

I'm uploaded gif for scenario . 

https://user-images.githubusercontent.com/5872984/112007217-8a9cee00-8b35-11eb-8dfb-40fa75dd6610.mp4

Thanks.

**Comment by embbnux** [comment] 2021-03-23 02:38
Thanks @mzahirr I reopen this issue. Will investigate more with your scenario.

**Comment by embbnux** [comment] 2021-03-24 09:31
hi @mzahirr I tested again, and it works at latest build. 
Can you help to collect HAR file and logs and send it to devsupport@ringcentral.com.
To collect HAR:
1. you need to open chrome developer tool firstly
2. then refresh web page
3. then reproduce it
4. save network request as HAR file.

**Comment by mzahirr** [comment] 2021-03-29 14:25
I have created ticket about that. thanks.

**Comment by embbnux** [comment] 2021-03-30 02:36
@mzahirr Can you share ticket number here?

**Comment by embbnux** [comment] 2021-04-01 06:36
@mzahirr As I mentioned in email, you need to update code to have the fix. 
I will close this case. Feel free to reopen it.

**Closed by embbnux** 2021-04-01 06:36 UTC
