### ISSUE TITLE
Have to go through sign-in process twice to log in

### ISSUE THREAD

**Issue by ElridgeDMello** [ringcentral/ringcentral-embeddable#229] opened 2019-04-29 17:57 UTC
Hello,

We are using the embeddable widget version 0.2.2 https://apps.ringcentral.com/integration/ringcentral-embeddable/0.2.2/adapter.js?appKey=...snip...&appServer=https://platform.devtest.ringcentral.com

but we're experiencing the following issue: We have to go through the sign in process twice for the widget to successfully log us in.  This behavior happens in both Sandbox and Production environments (i.e. when `appServer` value is set to https://platform.devtest.ringcentral.com or https://platform.ringcentral.com)

Screenshots of the issue below:

Widget loads and prompts to sign-in:

![image](https://user-images.githubusercontent.com/1136153/56914597-1dcc6680-6a7a-11e9-9906-9687f94a6982.png)

2. Enter phone number:
![image](https://user-images.githubusercontent.com/1136153/56915346-e2cb3280-6a7b-11e9-8109-256a76018179.png)

3. Enter password:
![image](https://user-images.githubusercontent.com/1136153/56915455-2aea5500-6a7c-11e9-8f2d-156b5e862890.png)

4. Authorize:
![image](https://user-images.githubusercontent.com/1136153/56915493-42c1d900-6a7c-11e9-9ee7-be90d8cf1586.png)

Login fails due to internal error:
![image](https://user-images.githubusercontent.com/1136153/56915500-4a817d80-6a7c-11e9-8bf6-86c7945d7a62.png)

Retrying...
*(Repeat steps 2, 3, 4)* results in:

![image](https://user-images.githubusercontent.com/1136153/56915548-700e8700-6a7c-11e9-8fd7-bacaa647c36d.png)

**Comment by embbnux** [comment] 2019-05-02 15:13
Hi @ElridgeDMello, 

Thanks so much for feedback. I think it is a bug in widget.
Can you provide javascript console logs in chrome developer tools. Our widget will log detail error messages for login fail. 

Thanks

**Comment by embbnux** [comment] 2019-05-08 08:31
@ElridgeDMello Can you still reproduce this. I checked in my side, and works well. Can you provide more details and logs for track this issue.

**Comment by ElridgeDMello** [comment] 2019-05-09 21:30
> @ElridgeDMello Can you still reproduce this. I checked in my side, and works well. Can you provide more details and logs for track this issue.

@embbnux I have not been able to reproduce the issue today.  I haven't changed versions of the widget, so wonder if something changed on the backend?

**Comment by embbnux** [comment] 2019-06-17 02:13
I think this is caused by some network issues. Will still track on this.

**Comment by embbnux** [comment] 2019-07-15 07:24
Found from other cases:
If we opened multiple pages (tabs) with RingCentral Embeddable in different environment (sandbox or production) or different RingCentral app id, when user logged in a tab, other tab will make app logout. So user needed to login again.

**Comment by embbnux** [comment] 2019-11-07 06:55
Closed by inactive. I think the root cause is as mentioned in upper message. Feel free to reopen if you got some issue.

**Closed by embbnux** 2019-11-07 06:55 UTC
