### ISSUE TITLE
bug: fax view/download button do not work

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/ringcentral-embeddable#449] opened 2020-11-06 00:57 UTC

**Comment by embbnux** [comment] 2020-11-12 03:17
A issue caused by chrome. after widget open a download link, user need to refresh the page to trigger download

**Comment by embbnux** [comment] 2020-11-12 03:24
Okay, we can fix it by add `contentDisposition=Attachment` in download link

**Comment by embbnux** [comment] 2020-11-24 09:51
voicemail download fixed in master build. Fax will be fixed after fixed in widgets lib

**Comment by embbnux** [comment] 2021-02-18 09:47
fixed

**Closed by embbnux** 2021-02-18 09:47 UTC
