### ISSUE TITLE
login number is not present in rc-login-status-notify event

### ISSUE THREAD

**Issue by mangatinanda** [ringcentral/ringcentral-embeddable#575] opened 2021-11-17 10:49 UTC
In the demo widget, the data that is being logged is `rc-login-status-notify: true *101`.  Main number is missing. This used to work before.

**Comment by embbnux** [comment] 2021-11-18 02:09
Hi @mangatinanda Can you help to collect logs and HAR for us to track this issue. When I tried today, I can't reproduce it in my side.
To collect logs and HAR file:
1. Open page with the widget, logout if it is logged.
2. Right click the widget's button and select Inspect to open Chrome developer tool.
3. Login with RingCentral account in the widget.
4. After logged, and you get login status notify, in Console panel right click to save logs
5. In Network panel, right click request to Save all as HAR with content.
6. Provide logs and HAR file here https://developers.ringcentral.com/support/create-case

**Comment by mangatinanda** [comment] 2021-11-18 17:09
I could not find an option to upload logs and HAR file.

Anyways, the issue is easily reproducible in the widget here: https://ringcentral.github.io/ringcentral-embeddable/ 

Here is console logs screenshot if that helps:
![Screenshot 2021-11-18 at 10 33 08 PM](https://user-images.githubusercontent.com/6745155/142462592-488458ec-f1aa-4189-8c09-d3b127266935.png)

In the code, I saw ```loginNumber = [this._accountInfo.mainCompanyNumber, extensionNumber].join('*',);```

I think this should be ```loginNumber = [this._accountInfo.mainNumber, extensionNumber].join('*',);```

**Comment by embbnux** [comment] 2021-11-19 08:29
Hi @mangatinanda I think I can reproduce this with a free RingCentral developer account in production environment (platform.ringcentral.com).
It is by design as free RingCentral developer account doesn't have main number.
Can you help to check if your login account is free account? If you want to test app with your free developer account, you need to change environment into sandbox platform.devtest.ringcentral.com. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

**Comment by mangatinanda** [comment] 2021-11-19 09:19
Hi @embbnux it is not a free RingCentral developer account. I can see the mainNumber in API call.
Endpoint: https://platform.ringcentral.com/restapi/v1.0/account/~
![Screenshot 2021-11-19 at 2 42 41 PM](https://user-images.githubusercontent.com/6745155/142597455-4f056ba5-2044-43db-8cb7-d24e394278ba.png)

I tested with both sandbox and a production account. Same result: `rc-login-status-notify: true *101`. I can see the mainNumber in the API call though.

**Comment by mangatinanda** [comment] 2021-11-19 09:39
@embbnux I just checked with the same account at https://ringcentral.github.io/ringcentral-embeddable/ and it is logging both main number and extension number. Not sure what has changed.

**Comment by embbnux** [comment] 2021-11-22 02:59
> @embbnux I just checked with the same account at https://ringcentral.github.io/ringcentral-embeddable/ and it is logging both main number and extension number. Not sure what has changed.

So it can work now? If you can still reproduce it, can you help to collect HAR and logs and send to devsupport@ringcentral.com, and share email title here? The HAR and logs can help us to track it.

**Comment by embbnux** [comment] 2021-11-22 09:03
Hi @mangatinanda I can reproduce it now. The root cause is that the event is sent before app get data from account info API.
It will be fixed soon.

**Closed** 2021-11-23 13:06 UTC
Labels: bug
